puts "Hello Iain"
puts "Hello Ian"
puts "Hello Eric"
puts "try not to drop-kick anyone today"
puts "The seagulls follow the trawler, because they know that fish will be thrown off the back of it.  Au revoir"
